name: meteo
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0-288.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.1.0
  dio: ^5.4.3+1
  flutter_map: ^7.0.1
  url_launcher: ^6.3.0
  sqflite: ^2.3.3+1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - .env
    - images/